### ISSUE TITLE
Eddystone TLM message not showing

### ISSUE THREAD

**Issue by atomusk** [sandeepmistry/node-eddystone-beacon-scanner#13]
Hello,

I am trying to get the Telemetry message from an Estimote tag (estimote OS A.3.2.0 & Hardware D3.4 configured as an eddystone), on an Edison Board, and the message does not show up.

I found a workaround in the noble project (flag NOBLE_REPORT_ALL_HCI_EVENTS=1), but wanted to raise the issue since it does impact the functionnality of this project.

Using the project basic.js exemple, the board manage to find the UID frame : 
```
found Eddystone Beacon:
 {
  "txPower": -50,
  "namespace": "edd1ebeac04e5defa017",
  "instance": "f4c683198fb6",
  "id": "f4c683198fb6",
  "type": "uid",
  "rssi": -71,
  "distance": 0.1,
  "lastSeen": 1451735137624
}
```
Following by several "updated" then a "Lost" (even thought I did not move the tag)

And I never get any TLM frame (when, with my phone, I can get the info with the estimote app).

Searching in the noble project I found in hci-socket/gap.js that adding "gap" debug flag, that I do get the TLM frame but as soon as I get a TLM frame, I don't get any Discover until I get the "Lost" response.

```
gap advertisement = {"localName":"EST","serviceData":[{"uuid":"feaa","data":[0,206,237,209,235,234,192,78,93,239,160,23,244,198,131,25,143,182]}],"serviceUuids":["feaa"]} +2s
  gap advertisement = {"localName":"EST","serviceData":[{"uuid":"feaa","data":[32,0,11,247,26,192,0,0,141,216,0,6,88,56]}],"serviceUuids":["feaa"]} +990ms
  gap advertisement = {"localName":"EST","serviceData":[{"uuid":"feaa","data":[0,206,237,209,235,234,192,78,93,239,160,23,244,198,131,25,143,182]}],"serviceUuids":["feaa"]} +1s
  gap advertisement = {"localName":"EST","serviceData":[{"uuid":"feaa","data":[0,206,237,209,235,234,192,78,93,239,160,23,244,198,131,25,143,182]}],"serviceUuids":["feaa"]} +2s
lost Eddystone beacon:
 {
  "txPower": -50,
  "namespace": "edd1ebeac04e5defa017",
[...]
```

And watching the gap.js code I found the NOBLE_REPORT_ALL_HCI_EVENTS flag and indeed launching my project prefixed by NOBLE_REPORT_ALL_HCI_EVENTS=1 I do get both messages.

Thank

**Comment by sandeepmistry** [comment]
@atomusk thanks for bring this up, the ```NOBLE_REPORT_ALL_HCI_EVENTS``` flag should be set, as noble expects BLE devices to have scan response data, which is not the case for Eddystone Beacon spec.

Would you have time to submit a pull request? The environment var should be set in the JS side (```lib/eddystone-beacon-scanner.js```):

```javascript
process.env['NOBLE_REPORT_ALL_HCI_EVENTS'] = 1;
```

**Comment by sandeepmistry** [comment]
This has been fixed in https://github.com/sandeepmistry/node-eddystone-beacon-scanner/commit/f24f6211532a1c1120d4a3a6ebfb2e285fe449df.
