### ISSUE TITLE
Units for Distance?

### ISSUE THREAD

**Issue by josephliccini** [sandeepmistry/node-eddystone-beacon-scanner#14]
Hi, we are using the 'Distance' from Eddystone URL to do some calculations, and we were wondering what units are used?

We though in Meters, but it didn't seem to be the case.

**Comment by sandeepmistry** [comment]
@josephliccini I believe it's in meters. @christopherdro can confirm. Maybe the beacon is not calibrated correctly for the ```Calibrated Tx power at 0 m``` is incorrect?

**Comment by christopherdro** [comment]
The calculation should be in meters.
The distance filter being used in this library was taken straight out of the android project on the eddystone repo. See: https://github.com/google/eddystone/blob/3925ce40925273090e60760425cbce490fc510b4/tools/eddystone-validator/EddystoneValidator/app/src/main/java/com/google/sample/eddystonevalidator/BeaconArrayAdapter.java#L58-L61

**Comment by josephliccini** [comment]
Thanks guys!

Just to clarify, this will only produce correct values if the ```tx power``` is set to 0dBm?  One of our beacons is set to +5 dBm for extended range:

![20160410_165340000_ios](https://cloud.githubusercontent.com/assets/7726025/14411643/4eef759e-ff1c-11e5-9825-18f496b3df3b.png)

**Comment by ukBaz** [comment]
Hello @josephliccini , 

the formula will be _accurate_ at a range of transmit powers. The [specification](https://github.com/google/eddystone/tree/master/eddystone-url#frame-specification) for Eddystone URL is that the advert will contain the tx power measured at 0 meters. This is different from the iBeacon spec I believe where the advert contains the measured tx value at 1m.
If the correct value is not being put in the advert then the result will be out is the point I think @sandeepmistry was making. 
There is more information on the formula in [this](https://docs.google.com/viewerng/viewer?url=http://cdn.intechopen.com/pdfs/13525.pdf&time=3ff091023b1963d89678d6d8b81d0145) paper with sections 2.1, 3.1.4 & 3.1.5 being probably the most relevant.
However accuracy is a tricky thing with RSSI as it will fluctuate quite a bit especially as the signal gets weaker.
The accuracy of RSSI for location is discussed in [this](https://www.beaconzone.co.uk/bluetoothleposition) article.

I hope something in that was useful.

**Comment by sandeepmistry** [comment]
@ukBaz @christopherdro thanks!

@josephliccini even though you've set the TX power to 5 dBm the beacon might not be updated the ```Calibrated Tx power at 0 m``` appropriately throwing off calculations.

I'm closing this for now, because as @christopherdro pointed out the exact same formula is used in the Eddystone beacon validator app. @josephliccini I suggest you try this app as well and compare to this module.
