### ISSUE TITLE
Typo in the readme

### ISSUE THREAD

**Issue by aBigSchwein** [sandeepmistry/node-eddystone-beacon-scanner#15]
Hey Sandeep, 

You need to change 
`EddystoneBeaconScanner.startScannning`

to 

`EddystoneBeaconScanner.startScanning`

**Comment by sandeepmistry** [comment]
Hi @aBigSchwein, thanks for bring this to my attention. I've corrected in https://github.com/sandeepmistry/node-eddystone-beacon-scanner/commit/3407d3783cf93a4f0bfbc4ac4d7d103142bb3e66.

Also, pull requests are always welcome for typo corrections or any other changes :)
