### ISSUE TITLE
npm refusing to install eddystone-beacon-scanner as a dependency of itself

### ISSUE THREAD

**Issue by RajPratim21** [sandeepmistry/node-eddystone-beacon-scanner#16]
got above message while trying to install node-eddystone-beacon-scanner
on ubuntu 16.04 under proxy (proxy has been set)
can anyone help me with above

**Comment by sandeepmistry** [comment]
Hi @RajPratim21,

Maybe you are trying to run npm install in a folder name `eddystone-beacon-scanner`?

I'd suggest to make a `~/test` directory and try to install in there. Let me know if this doesn't work.
