### ISSUE TITLE
Not finding beacon after it's lost

### ISSUE THREAD

**Issue by derekshull** [sandeepmistry/node-eddystone-beacon-scanner#17]
I'm running the scanner and it shows my beacon the first time it finds it, it shows the updates, and when I turn the beacon off, it will show that it's been lost.  Though when I turn the beacon back on it doesn't show the beacon to the found or updated again.  Is this possible?

**Comment by derekshull** [comment]
Update: If I run the scanner it picks up the beacons.  If I walk away from the raspberry pi with the beacon in my hand it shows the beacon as lost, and when I return to the raspberry pi with the beacon in my hand it shows the beacon as found again.  Though if I just turn the beacon off, it shows the beacon as lost but when I turn the beacon back on it won't show the beacon as found.  Very strange.  

Is there a way to make the beacon found when I turn it off and back on again?

**Comment by sandeepmistry** [comment]
@derekshull there's probably a logic error in the code: https://github.com/sandeepmistry/node-eddystone-beacon-scanner/blob/master/lib/eddystone-beacon-scanner.js#L54-L85

Do you have time to dive in and take a closer look? Maybe when a beacon is lost the entry is not cleared correctly?

**Comment by sandeepmistry** [comment]
@derekshull ping ...

**Comment by sandeepmistry** [comment]
Closing this for now due to lack of activity ...
