### ISSUE TITLE
Make the grace period configurable

### ISSUE THREAD

**Issue by ValentinGot** [sandeepmistry/node-eddystone-beacon-scanner#18]
Hi,

Would you be ok if i made a quick PR to make the grace periode configurable ?
Something like:
```js
EddystoneBeaconScanner.startScanning(true, 30000); // Increase the grace period to 30s
```

Of course the default grace period would always be of 5 seconds.

Very nice job btw :)

**Comment by sandeepmistry** [comment]
@ValentinGot for sure!

**Comment by ValentinGot** [comment]
Made the PR [#19](https://github.com/sandeepmistry/node-eddystone-beacon-scanner/pull/19) :)
